# -*- coding: utf-8 -*-
# Remaining 20 articles — full EN/FR professional veterinary terminology.
# Merged in build_en_fr_v5.py via TRANSLATIONS.update(TRANSLATIONS_BATCH2)

TRANSLATIONS_BATCH2 = {
    "mascotasinpapeles": {
        "en": {
            "title": "Travelling with a pet without papers: risks and legal consequences",
            "description": "Technical analysis of the risks of international pet travel without proper health documentation. By Dr Jessica Camacho, Zoovet Travel.",
            "h1": "Travelling with a pet without papers: risks and legal consequences",
            "body": "<p>Attempting to cross an international border with a companion animal without the Official Veterinary Export Certificate and destination-compliant documentation is not a minor administrative oversight. It leads to <strong>immediate rejection at customs</strong>, mandatory quarantine at the expense of the owner, or return of the animal to the country of origin. Health authorities do not accept verbal declarations or private health certificates in place of the official chain required by EU Regulation 576/2013 and equivalent frameworks.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentary chain and official endorsement</h2>\n<p>The export process requires an ISO 11784/11785 FDX-B compliant microchip, rabies vaccination compliant with international movement regulations, and in many destinations a Rabies Neutralising Antibody Titration Test (RNATT) with a result ≥ 0.5 IU/mL. The Official Veterinary Export Certificate (CZE) issued by the competent authority (e.g. SENASA in Peru) must be endorsed within the validity period of the clinical examination. Without this chain, the animal has no legal status for entry.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Contact a veterinarian specialised in international pet movement to build the file from the microchip and vaccination dates. Zoovet Travel has been managing export processes from Trujillo for 12 years. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707. Do not risk your companion's safety or your investment.</p>",
        },
        "fr": {
            "title": "Voyager avec un animal sans papiers : risques et conséquences juridiques",
            "description": "Analyse technique des risques du voyage international avec animal sans documentation sanitaire adéquate. Par la Dre Jessica Camacho, Zoovet Travel.",
            "h1": "Voyager avec un animal sans papiers : risques et conséquences juridiques",
            "body": "<p>Tenter de franchir une frontière internationale avec un animal de compagnie sans certificat vétérinaire officiel d'exportation et sans documentation conforme à la destination n'est pas une simple négligence administrative. Cela entraîne un <strong>rejet immédiat en douane</strong>, une quarantaine obligatoire à la charge du propriétaire ou le retour de l'animal au pays d'origine. Les autorités sanitaires n'acceptent ni déclarations verbales ni certificats de santé privés à la place de la chaîne officielle exigée par le Règlement UE 576/2013 et cadres équivalents.</p>\n<h2><span class=\"sec-label\">Section 1</span> Chaîne documentaire et visa officiel</h2>\n<p>Le processus d'exportation exige un transpondeur conforme ISO 11784/11785 FDX-B, une vaccination antirabique conforme aux exigences réglementaires internationales et, pour de nombreuses destinations, un titrage sérologique des anticorps antirabiques (RNATT) avec un résultat ≥ 0,5 UI/mL. Le certificat vétérinaire officiel d'exportation (CZE) délivré par l'autorité compétente (ex. SENASA au Pérou) doit être visé dans le délai de validité de l'examen clinique. Sans cette chaîne, l'animal n'a pas de statut juridique pour l'entrée.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Contactez un vétérinaire spécialisé en mouvement international des animaux de compagnie pour constituer le dossier à partir des dates de puce et de vaccination. Zoovet Travel gère les processus d'exportation depuis Trujillo depuis 12 ans. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707. Ne mettez pas en jeu la sécurité de votre compagnon ni votre investissement.</p>",
        },
    },
    "viaja-chile-argentina": {
        "en": {
            "title": "Requirements to take your pet to Chile and Argentina",
            "description": "Technical guide on entry requirements for dogs and cats from Peru to Chile and Argentina. Official certificates and health protocols by Dr Jessica Camacho.",
            "h1": "Requirements to take your pet to Chile and Argentina",
            "body": "<p>Entry of dogs and cats into Chile and Argentina from Peru is governed by official health protocols that require an <strong>Official Veterinary Export Certificate</strong> and compliance with vaccination and deworming windows. Each country maintains its own import conditions; assuming that what works for one applies to the other is a frequent cause of rejection at the border.</p>\n<h2><span class=\"sec-label\">Section 1</span> Common regulatory framework</h2>\n<p>Both countries require identification by ISO 11784/11785 compliant microchip, rabies vaccination compliant with international movement regulations, and in many cases internal and external parasite treatment within a defined period before travel. The health certificate must be issued by an authorised veterinarian and endorsed by the competent authority (e.g. SENASA for Peru). Validity of the clinical examination is usually 10 days or less; verification with the destination authority is mandatory.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm the current requirements with the official portals of SAG (Chile) and SENASA Argentina before scheduling the export certificate. Zoovet Travel prepares the documentary chain from Trujillo for both destinations. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Conditions d'entrée d'un animal de compagnie au Chili et en Argentine",
            "description": "Guide technique sur les exigences d'entrée des chiens et chats du Pérou vers le Chili et l'Argentine. Certificats officiels et protocoles sanitaires par la Dre Jessica Camacho.",
            "h1": "Conditions d'entrée d'un animal de compagnie au Chili et en Argentine",
            "body": "<p>L'entrée des chiens et chats au Chili et en Argentine depuis le Pérou est régie par des protocoles sanitaires officiels qui exigent un <strong>certificat vétérinaire officiel d'exportation</strong> et le respect des fenêtres de vaccination et de déparasitation. Chaque pays conserve ses propres conditions d'importation ; supposer que ce qui vaut pour l'un vaut pour l'autre est une cause fréquente de rejet à la frontière.</p>\n<h2><span class=\"sec-label\">Section 1</span> Cadre réglementaire commun</h2>\n<p>Les deux pays exigent l'identification par puce conforme ISO 11784/11785, la vaccination antirabique conforme aux exigences réglementaires internationales et souvent un traitement antiparasitaire interne et externe dans un délai défini avant le voyage. Le certificat de santé doit être délivré par un vétérinaire habilité et visé par l'autorité compétente (ex. SENASA pour le Pérou). La validité de l'examen clinique est généralement de 10 jours ou moins ; la vérification auprès de l'autorité de destination est obligatoire.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez les exigences en vigueur auprès des portails officiels du SAG (Chili) et du SENASA Argentine avant de programmer le certificat d'exportation. Zoovet Travel prépare la chaîne documentaire depuis Trujillo pour les deux destinations. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "viajar_mascotas_australia_proceso_mas_estricto_editorial": {
        "en": {
            "title": "Taking your pet to Australia: the strictest import process",
            "description": "Technical guide on Australian pet import requirements: RNATT, quarantine and official certification. By Dr Jessica Camacho, Zoovet Travel.",
            "h1": "Taking your pet to Australia: the strictest import process",
            "body": "<p>Australia applies one of the most demanding companion animal import protocols globally. <strong>Requirements to take your pet to Australia</strong> include an ISO 11784/11785 compliant microchip implanted before vaccination, rabies vaccination, a Rabies Neutralising Antibody Titration Test (RNATT) with result ≥ 0.5 IU/mL from an approved laboratory, and mandatory quarantine on arrival. The process is measured in months, not weeks.</p>\n<h2><span class=\"sec-label\">Section 1</span> DAFF requirements and quarantine</h2>\n<p>The Department of Agriculture, Fisheries and Forestry (DAFF) publishes and updates the import conditions. The blood sample for RNATT must be drawn at least 30 days after primary vaccination and must be processed by an OIE-accredited laboratory. Post-arrival quarantine duration depends on the country of origin and compliance with pre-export treatments. Any error in the documentary or treatment sequence can result in extended quarantine or refusal of entry.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Plan the calendar from the microchip and vaccination dates with a veterinarian specialised in international export. Zoovet Travel manages the full chain from Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Emmener son animal en Australie : le processus d'importation le plus strict",
            "description": "Guide technique sur les exigences d'importation d'animaux en Australie : RNATT, quarantaine et certification officielle. Par la Dre Jessica Camacho, Zoovet Travel.",
            "h1": "Emmener son animal en Australie : le processus d'importation le plus strict",
            "body": "<p>L'Australie applique l'un des protocoles d'importation d'animaux de compagnie les plus exigeants au monde. Les <strong>conditions pour emmener son animal en Australie</strong> comprennent une puce conforme ISO 11784/11785 implantée avant la vaccination, la vaccination antirabique, un titrage sérologique des anticorps antirabiques (RNATT) avec résultat ≥ 0,5 UI/mL par un laboratoire approuvé, et une quarantaine obligatoire à l'arrivée. Le processus se compte en mois, pas en semaines.</p>\n<h2><span class=\"sec-label\">Section 1</span> Exigences du DAFF et quarantaine</h2>\n<p>Le Department of Agriculture, Fisheries and Forestry (DAFF) publie et met à jour les conditions d'importation. Le prélèvement sanguin pour le RNATT doit être effectué au moins 30 jours après la primovaccination et traité par un laboratoire accrédité OIE. La durée de la quarantaine à l'arrivée dépend du pays d'origine et du respect des traitements pré-exportation. Toute erreur dans la séquence documentaire ou de traitements peut entraîner une quarantaine prolongée ou un refus d'entrée.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Planifiez le calendrier à partir des dates de puce et de vaccination avec un vétérinaire spécialisé en exportation internationale. Zoovet Travel gère la chaîne complète depuis Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "llevar_mascota_japon_proceso_que_pocos_intentan": {
        "en": {
            "title": "Taking your pet to Japan: a process few attempt",
            "description": "Technical guide on Japanese pet import requirements: microchip, vaccination, RNATT and official certification. By Dr Jessica Camacho.",
            "h1": "Taking your pet to Japan: a process few attempt",
            "body": "<p>Japan requires strict compliance with identification, vaccination and serology protocols. <strong>Requirements to take your pet to Japan</strong> include an ISO 11784/11785 FDX-B compliant microchip, rabies vaccination, and a Rabies Neutralising Antibody Titration Test (RNATT) from an approved laboratory with result ≥ 0.5 IU/mL. The sample must be drawn at least 30 days after primary vaccination. Advance notification and official health certificate endorsed by the exporting country are mandatory.</p>\n<h2><span class=\"sec-label\">Section 1</span> MAFF and post-arrival procedures</h2>\n<p>The Ministry of Agriculture, Forestry and Fisheries (MAFF) sets import conditions. The official veterinary export certificate must be issued within the validity period required by Japan and must be presented at the port of entry. Failure to comply with the chronological order (microchip before vaccination, sampling after day 30) invalidates the process and forces a restart of the protocol.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Work with a veterinarian experienced in Japanese import requirements to avoid costly resets. Zoovet Travel manages the full documentary and clinical chain from Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Emmener son animal au Japon : un processus que peu tentent",
            "description": "Guide technique sur les exigences d'importation au Japon : puce, vaccination, RNATT et certification officielle. Par la Dre Jessica Camacho.",
            "h1": "Emmener son animal au Japon : un processus que peu tentent",
            "body": "<p>Le Japon exige le respect strict des protocoles d'identification, de vaccination et de sérologie. Les <strong>conditions pour emmener son animal au Japon</strong> comprennent une puce conforme ISO 11784/11785 FDX-B, la vaccination antirabique et un titrage sérologique des anticorps antirabiques (RNATT) par un laboratoire approuvé avec résultat ≥ 0,5 UI/mL. Le prélèvement doit être effectué au moins 30 jours après la primovaccination. La notification préalable et le certificat de santé officiel visé par le pays exportateur sont obligatoires.</p>\n<h2><span class=\"sec-label\">Section 1</span> MAFF et procédures à l'arrivée</h2>\n<p>Le Ministry of Agriculture, Forestry and Fisheries (MAFF) fixe les conditions d'importation. Le certificat vétérinaire officiel d'exportation doit être délivré dans le délai de validité exigé par le Japon et présenté au port d'entrée. Le non-respect de l'ordre chronologique (puce avant vaccin, prélèvement après le jour 30) invalide le processus et impose une réinitialisation du protocole.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Travailler avec un vétérinaire expérimenté aux exigences d'importation japonaises pour éviter des recommencements coûteux. Zoovet Travel gère la chaîne documentaire et clinique complète depuis Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "articulo_rechazo_aduana_mascota": {
        "en": {
            "title": "Pet rejected at customs: causes and how to avoid them",
            "description": "Technical analysis of the main causes of pet rejection at border control and how to prevent them. By Dr Jessica Camacho, Zoovet Travel.",
            "h1": "Pet rejected at customs: causes and how to avoid them",
            "body": "<p><strong>Rejection of a pet at customs</strong> is usually due to documentary non-compliance: expired health certificate, vaccination applied after the microchip, serological sample drawn before day 30, or certificate not endorsed by the competent authority. Border inspectors do not have discretion to accept incomplete or out-of-date documentation; the animal is held, returned or placed in quarantine at the owner's expense.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentary and sequence errors</h2>\n<p>The most frequent causes include: health certificate validity exceeded (often 10 days or 48 hours depending on destination), rabies vaccination not compliant with international movement regulations or applied before microchip implantation, RNATT sample taken before 30 days after primary vaccination, or Official Veterinary Export Certificate without official endorsement by the exporting country (e.g. SENASA).</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Build the entire chain with a veterinarian specialised in international pet movement and validate dates with the destination authority before travel. Zoovet Travel has been managing exports from Trujillo for 12 years. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Animal refusé en douane : causes et comment les éviter",
            "description": "Analyse technique des principales causes de refus d'animal en douane et comment les prévenir. Par la Dre Jessica Camacho, Zoovet Travel.",
            "h1": "Animal refusé en douane : causes et comment les éviter",
            "body": "<p>Le <strong>refus d'un animal en douane</strong> est le plus souvent dû à une non-conformité documentaire : certificat de santé expiré, vaccination appliquée après la puce, prélèvement sérologique avant le jour 30, ou certificat non visé par l'autorité compétente. Les inspecteurs frontaliers n'ont pas la faculté d'accepter une documentation incomplète ou périmée ; l'animal est retenu, renvoyé ou mis en quarantaine aux frais du propriétaire.</p>\n<h2><span class=\"sec-label\">Section 1</span> Erreurs documentaires et de séquence</h2>\n<p>Les causes les plus fréquentes comprennent : validité du certificat de santé dépassée (souvent 10 jours ou 48 h selon la destination), vaccination antirabique non conforme aux exigences réglementaires internationales ou appliquée avant l'implantation de la puce, prélèvement RNATT avant 30 jours après la primovaccination, ou certificat vétérinaire officiel d'exportation sans visa officiel du pays exportateur (ex. SENASA).</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Constituer toute la chaîne avec un vétérinaire spécialisé en mouvement international des animaux et valider les dates auprès de l'autorité de destination avant le voyage. Zoovet Travel gère les exportations depuis Trujillo depuis 12 ans. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "articulo_cuanto_tiempo_antes_viaje_mascota": {
        "en": {
            "title": "How long before the trip should you prepare your pet for travel?",
            "description": "Technical guide on lead times for microchip, vaccination, RNATT and official certificate when planning international pet travel. By Dr Jessica Camacho.",
            "h1": "How long before the trip should you prepare your pet for travel?",
            "body": "<p><strong>How long before the trip</strong> to start the process depends on the destination. For EU-compliant movement, a minimum of 21 days after primary rabies vaccination is required; if the destination requires a Rabies Neutralising Antibody Titration Test (RNATT), the blood sample cannot be drawn before 30 days after primary vaccination, and laboratory turnaround plus possible waiting periods can extend the timeline to several months.</p>\n<h2><span class=\"sec-label\">Section 1</span> Planning from the destination backwards</h2>\n<p>Start from the intended departure date and work backwards: subtract the validity period of the health certificate (often 10 days or 48 hours), the time needed for official endorsement, and for RNATT destinations the 30-day post-vaccination window plus laboratory and any quarantine periods. Last-minute preparation is the main cause of rescheduled flights and stress for the family and the animal.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm destination requirements and build the calendar with a veterinarian specialised in international export. Zoovet Travel designs the schedule from Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Combien de temps avant le voyage préparer son animal ?",
            "description": "Guide technique sur les délais de puce, vaccination, RNATT et certificat officiel pour planifier un voyage international avec animal. Par la Dre Jessica Camacho.",
            "h1": "Combien de temps avant le voyage préparer son animal ?",
            "body": "<p><strong>Combien de temps avant le voyage</strong> commencer dépend de la destination. Pour un mouvement conforme à l'UE, un minimum de 21 jours après la primovaccination antirabique est requis ; si la destination exige un titrage sérologique des anticorps antirabiques (RNATT), le prélèvement sanguin ne peut pas être effectué avant 30 jours après la primovaccination, et le délai de laboratoire plus d'éventuelles périodes d'attente peut prolonger le calendrier à plusieurs mois.</p>\n<h2><span class=\"sec-label\">Section 1</span> Planifier à partir de la destination à l'envers</h2>\n<p>Partez de la date de départ prévue et remontez : soustrayez la validité du certificat de santé (souvent 10 jours ou 48 h), le délai nécessaire pour le visa officiel, et pour les destinations RNATT la fenêtre de 30 jours post-vaccination plus le laboratoire et d'éventuelles quarantaines. La préparation de dernière minute est la cause principale de vols reprogrammés et de stress pour la famille et l'animal.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez les exigences de la destination et construisez le calendrier avec un vétérinaire spécialisé en exportation internationale. Zoovet Travel conçoit le planning depuis Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "articulo_certificado_zoosanitario_senasa_trujillo": {
        "en": {
            "title": "Official veterinary export certificate (SENASA) in Trujillo",
            "description": "Technical guide on obtaining the Official Veterinary Export Certificate (CZE) via SENASA in Trujillo, Peru. By Dr Jessica Camacho.",
            "h1": "Official veterinary export certificate (SENASA) in Trujillo",
            "body": "<p>The <strong>Official Veterinary Export Certificate (CZE)</strong> is the document issued by the competent health authority (in Peru, SENASA — National Agrarian Health Service) that certifies that the animal meets the destination country's import requirements. It is not issued by the private veterinarian; the veterinarian prepares the health certificate and the file that is then validated and endorsed by the official inspector.</p>\n<h2><span class=\"sec-label\">Section 1</span> Where and how to process it in Trujillo</h2>\n<p>In La Libertad, the final inspection and issuance are centralised at the SENASA office at the Services Complex on the Panamericana Norte highway. The animal must be presented with the complete file: microchip reading, vaccination record, health certificate from the authorised veterinarian, and proof of payment of fees. The inspector verifies the documentary chain and performs in-person microchip reading; if the transponder is not ISO 11784/11785 compliant or is undetectable, the process stops.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Coordinate with a registered veterinarian who manages the VUCE and the clinical basis so that the appointment at SENASA is smooth. Zoovet Travel has been managing this process from Trujillo for 12 years. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Certificat zoosanitaire officiel d'exportation (SENASA) à Trujillo",
            "description": "Guide technique sur l'obtention du certificat vétérinaire officiel d'exportation (CZE) via le SENASA à Trujillo, Pérou. Par la Dre Jessica Camacho.",
            "h1": "Certificat zoosanitaire officiel d'exportation (SENASA) à Trujillo",
            "body": "<p>Le <strong>certificat vétérinaire officiel d'exportation (CZE)</strong> est le document délivré par l'autorité sanitaire compétente (au Pérou, le SENASA — Service national de santé agraire) qui atteste que l'animal satisfait aux exigences d'importation du pays de destination. Il n'est pas délivré par le vétérinaire privé ; le vétérinaire prépare le certificat de santé et le dossier qui sont ensuite validés et visés par l'inspecteur officiel.</p>\n<h2><span class=\"sec-label\">Section 1</span> Où et comment le faire délivrer à Trujillo</h2>\n<p>À La Libertad, l'inspection finale et la délivrance sont centralisées au bureau du SENASA au Complexe de services sur la Carretera Panamericana Norte. L'animal doit être présenté avec le dossier complet : lecture de puce, carnet de vaccination, certificat de santé du vétérinaire habilité et preuve de paiement des redevances. L'inspecteur vérifie la chaîne documentaire et effectue la lecture de puce en présentiel ; si le transpondeur n'est pas conforme ISO 11784/11785 ou n'est pas détectable, le processus s'arrête.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Coordonnez avec un vétérinaire inscrit qui gère le VUCE et la base clinique pour que le rendez-vous au SENASA se déroule sans accroc. Zoovet Travel gère ce processus depuis Trujillo depuis 12 ans. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "gatosbodegaavion": {
        "en": {
            "title": "Cats in the aircraft hold: risks and preparation",
            "description": "Veterinary technical guide on the safety of cats travelling in the cargo hold. Hypoxia, stress and fit-to-fly assessment. By Dr Jessica Camacho.",
            "h1": "Cats in the aircraft hold: risks and preparation",
            "body": "<p><strong>Cats travelling in the aircraft hold</strong> are exposed to pressurised cabin equivalent altitude (about 6,000–8,000 feet), reduced partial pressure of oxygen, and isolation stress. Not all cats are suitable for cargo transport; those with cardiac, respiratory or renal compromise, or extreme stress, are at increased risk. Pharmacological sedation is contraindicated and prohibited by most airlines.</p>\n<h2><span class=\"sec-label\">Section 1</span> Physiological and behavioural factors</h2>\n<p>Preparation includes ethological conditioning to the carrier for several weeks, health assessment to rule out subclinical disease, and use of an IATA LAR-compliant crate with adequate ventilation and space. Thermal risk is highest on the ground; avoid layovers in hot climates. Hydration must be managed without spillage (drip drinkers or frozen water).</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>A fit-to-fly assessment by a veterinarian experienced in air transport is essential. Zoovet Travel performs this evaluation and carrier audit in Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Chats en soute : risques et préparation",
            "description": "Guide technique vétérinaire sur la sécurité des chats voyageant en soute. Hypoxie, stress et évaluation fit-to-fly. Par la Dre Jessica Camacho.",
            "h1": "Chats en soute : risques et préparation",
            "body": "<p>Les <strong>chats voyageant en soute</strong> sont exposés à l'altitude équivalente de cabine pressurisée (environ 6 000 à 8 000 pieds), à la baisse de la pression partielle d'oxygène et au stress d'isolement. Tous les chats ne sont pas aptes au transport en cargo ; ceux présentant une atteinte cardiaque, respiratoire ou rénale, ou un stress extrême, ont un risque accru. La sédation pharmacologique est contre-indiquée et interdite par la plupart des compagnies.</p>\n<h2><span class=\"sec-label\">Section 1</span> Facteurs physiologiques et comportementaux</h2>\n<p>La préparation inclut un conditionnement éthologique au transport sur plusieurs semaines, un bilan de santé pour écarter une pathologie infraclinique et l'utilisation d'une caisse conforme IATA LAR avec ventilation et espace suffisants. Le risque thermique est maximal au sol ; évitez les escales en climat chaud. L'hydratation doit être gérée sans déversement (abreuvoirs à goutte ou eau congelée).</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Une évaluation fit-to-fly par un vétérinaire expérimenté en transport aérien est indispensable. Zoovet Travel réalise cette évaluation et l'audit du transport à Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "transportindeal": {
        "en": {
            "title": "Pet transport in the aircraft hold: what you need to know",
            "description": "Technical guide on hold transport: pressurisation, temperature, IATA LAR crate and fit-to-fly assessment. By Dr Jessica Camacho, Zoovet Travel.",
            "h1": "Pet transport in the aircraft hold: what you need to know",
            "body": "<p><strong>Pet transport in the aircraft hold</strong> is subject to IATA Live Animals Regulations (LAR) and airline-specific restrictions. The hold is pressurised and climate-controlled in flight, but the highest thermal risk occurs on the ground during loading and layovers. The crate must allow the animal to stand, turn and lie down naturally; sedation is prohibited by most carriers and increases the risk of death.</p>\n<h2><span class=\"sec-label\">Section 1</span> Safety and documentation</h2>\n<p>Beyond documentation (microchip, vaccination, official certificate), a physiological assessment is required to confirm that the animal can tolerate mild hypoxia and metabolic stress. Brachycephalic breeds and animals with cardiac or respiratory compromise are often unsuitable for cargo. Zoovet Travel performs fit-to-fly assessment and carrier audits in Trujillo.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707 to schedule a technical consultation and validate your companion's fitness for hold travel.</p>",
        },
        "fr": {
            "title": "Transport des animaux en soute : ce qu'il faut savoir",
            "description": "Guide technique sur le transport en soute : pressurisation, température, caisse IATA LAR et évaluation fit-to-fly. Par la Dre Jessica Camacho, Zoovet Travel.",
            "h1": "Transport des animaux en soute : ce qu'il faut savoir",
            "body": "<p>Le <strong>transport des animaux en soute</strong> est soumis au Règlement IATA sur les animaux vivants (LAR) et aux restrictions de chaque compagnie. La soute est pressurisée et climatisée en vol, mais le risque thermique le plus élevé survient au sol lors du chargement et des escales. La caisse doit permettre à l'animal de se tenir debout, tourner et se coucher naturellement ; la sédation est interdite par la plupart des transporteurs et augmente le risque de décès.</p>\n<h2><span class=\"sec-label\">Section 1</span> Sécurité et documentation</h2>\n<p>Au-delà de la documentation (puce, vaccination, certificat officiel), une évaluation physiologique est nécessaire pour confirmer que l'animal tolère l'hypoxie légère et le stress métabolique. Les races brachycéphales et les animaux avec atteinte cardiaque ou respiratoire sont souvent inaptes au cargo. Zoovet Travel réalise l'évaluation fit-to-fly et l'audit des transporteurs à Trujillo.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707 pour prendre rendez-vous pour une consultation technique et valider l'aptitude de votre compagnon au voyage en soute.</p>",
        },
    },
    "viajarconpug": {
        "en": {
            "title": "Travelling with a pug: brachycephalic risks and hold transport",
            "description": "Technical guide on travelling with brachycephalic dogs (pug): respiratory risk in the hold and fit-to-fly assessment. By Dr Jessica Camacho.",
            "h1": "Travelling with a pug: brachycephalic risks and hold transport",
            "body": "<p><strong>Travelling with a pug</strong> in the aircraft hold carries increased risk due to brachycephalic obstructive airway syndrome (BOAS). Reduced partial pressure of oxygen at cruise altitude and stress can trigger respiratory distress, overheating and collapse. Many airlines restrict or prohibit brachycephalic breeds in cargo; cabin travel (where permitted by size) or alternative transport must be evaluated.</p>\n<h2><span class=\"sec-label\">Section 1</span> Assessment and preparation</h2>\n<p>A thorough cardiorespiratory assessment and, if indicated, imaging are necessary before considering hold transport. The crate must be IATA LAR compliant with ample ventilation. Sedation is contraindicated. Zoovet Travel assesses brachycephalic patients in Trujillo and advises on the viability of air transport for each case.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707 for a fit-to-fly consultation.</p>",
        },
        "fr": {
            "title": "Voyager avec un carlin : risques brachycéphales et transport en soute",
            "description": "Guide technique sur le voyage avec chien brachycéphale (carlin) : risque respiratoire en soute et évaluation fit-to-fly. Par la Dre Jessica Camacho.",
            "h1": "Voyager avec un carlin : risques brachycéphales et transport en soute",
            "body": "<p><strong>Voyager avec un carlin</strong> en soute comporte un risque accru en raison du syndrome obstructif des voies respiratoires des brachycéphales (BOAS). La baisse de pression partielle d'oxygène en croisière et le stress peuvent déclencher détresse respiratoire, surchauffe et collapsus. De nombreuses compagnies restreignent ou interdisent les races brachycéphales en cargo ; le voyage en cabine (si autorisé par la taille) ou un transport alternatif doit être évalué.</p>\n<h2><span class=\"sec-label\">Section 1</span> Évaluation et préparation</h2>\n<p>Un bilan cardiorespiratoire complet et, si indiqué, une imagerie sont nécessaires avant d'envisager le transport en soute. La caisse doit être conforme IATA LAR avec une ventilation suffisante. La sédation est contre-indiquée. Zoovet Travel évalue les patients brachycéphales à Trujillo et conseille sur la viabilité du transport aérien pour chaque cas.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707 pour une consultation fit-to-fly.</p>",
        },
    },
    "prepararatuperro": {
        "en": {
            "title": "Preparing your dog for international travel",
            "description": "Technical guide on preparing your dog for international travel: documentation, crate training and health assessment. By Dr Jessica Camacho, Zoovet Travel.",
            "h1": "Preparing your dog for international travel",
            "body": "<p><strong>Preparing your dog for international travel</strong> involves the documentary chain (microchip, rabies vaccination compliant with international movement regulations, and where required RNATT and official certificate), plus physiological and behavioural preparation. Crate conditioning for at least several weeks reduces stress during the flight; a dog that has never been confined in the crate may panic in the hold.</p>\n<h2><span class=\"sec-label\">Section 1</span> Health and logistics</h2>\n<p>Fit-to-fly assessment rules out subclinical cardiac or respiratory disease that could worsen at altitude. The crate must meet IATA LAR standards. Avoid heavy meals before departure to reduce intestinal gas expansion. Zoovet Travel prepares dogs for export from Trujillo with full clinical and documentary support.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707 to plan the process and schedule the health assessment.</p>",
        },
        "fr": {
            "title": "Préparer son chien pour un voyage international",
            "description": "Guide technique pour préparer son chien au voyage international : documentation, familiarisation à la caisse et bilan de santé. Par la Dre Jessica Camacho, Zoovet Travel.",
            "h1": "Préparer son chien pour un voyage international",
            "body": "<p><strong>Préparer son chien pour un voyage international</strong> implique la chaîne documentaire (puce, vaccination antirabique conforme aux exigences réglementaires internationales, et si nécessaire RNATT et certificat officiel), plus la préparation physiologique et comportementale. La familiarisation à la caisse pendant au moins plusieurs semaines réduit le stress pendant le vol ; un chien qui n'a jamais été enfermé dans la caisse peut paniquer en soute.</p>\n<h2><span class=\"sec-label\">Section 1</span> Santé et logistique</h2>\n<p>L'évaluation fit-to-fly écarte une pathologie cardiaque ou respiratoire infraclinique qui pourrait s'aggraver en altitude. La caisse doit respecter les normes IATA LAR. Évitez les repas lourds avant le départ pour limiter l'expansion des gaz intestinaux. Zoovet Travel prépare les chiens à l'exportation depuis Trujillo avec un accompagnement clinique et documentaire complet.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707 pour planifier le processus et programmer le bilan de santé.</p>",
        },
    },
    "llevar_gato_estados_unidos_desde_peru_guia_2026_editorial_v2": {
        "en": {
            "title": "Taking your cat to the United States from Peru: 2026 guide",
            "description": "Technical guide on US entry requirements for cats from Peru: CDC rules, vaccination and health certificate. By Dr Jessica Camacho.",
            "h1": "Taking your cat to the United States from Peru: 2026 guide",
            "body": "<p><strong>Requirements to take your cat to the United States from Peru</strong> are set by the CDC and USDA. From August 2024, dog entry rules changed significantly; cat entry may require a valid rabies vaccination and health certificate. Requirements vary according to the country of origin's rabies classification. Verification with the official CDC and USDA portals and with the airline is mandatory before travel.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentation and timing</h2>\n<p>Identification by ISO 11784/11785 compliant microchip, rabies vaccination compliant with international movement regulations, and a health certificate issued within the validity period required by the US are standard. For high-risk countries, additional serology or quarantine may apply. The certificate must be endorsed by the competent authority of the exporting country (e.g. SENASA for Peru).</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm current CDC/USDA requirements and build the file with a veterinarian specialised in US import. Zoovet Travel manages the process from Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>",
        },
        "fr": {
            "title": "Emmener son chat aux États-Unis depuis le Pérou : guide 2026",
            "description": "Guide technique sur les exigences d'entrée aux États-Unis pour les chats depuis le Pérou : règles CDC, vaccination et certificat de santé. Par la Dre Jessica Camacho.",
            "h1": "Emmener son chat aux États-Unis depuis le Pérou : guide 2026",
            "body": "<p>Les <strong>conditions pour emmener son chat aux États-Unis depuis le Pérou</strong> sont fixées par le CDC et l'USDA. Depuis août 2024, les règles d'entrée des chiens ont beaucoup changé ; l'entrée des chats peut exiger une vaccination antirabique en cours de validité et un certificat de santé. Les exigences varient selon la classification rage du pays d'origine. La vérification auprès des portails officiels CDC et USDA et auprès de la compagnie est obligatoire avant le voyage.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentation et délais</h2>\n<p>L'identification par puce conforme ISO 11784/11785, la vaccination antirabique conforme aux exigences réglementaires internationales et un certificat de santé délivré dans le délai de validité exigé par les États-Unis sont la norme. Pour les pays à haut risque, une sérologie complémentaire ou une quarantaine peuvent s'appliquer. Le certificat doit être visé par l'autorité compétente du pays exportateur (ex. SENASA pour le Pérou).</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez les exigences actuelles du CDC/USDA et constituez le dossier avec un vétérinaire spécialisé en importation vers les États-Unis. Zoovet Travel gère le processus depuis Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>",
        },
    },
    "viajeanimalgeriatrico": {
        "en": {
            "title": "Travelling with a geriatric pet: risks and preparation",
            "description": "Veterinary technical guide on international travel with elderly dogs and cats: physiological risk and fit-to-fly assessment. By Dr Jessica Camacho.",
            "h1": "Travelling with a geriatric pet: risks and preparation",
            "body": "<p><strong>Travelling with a geriatric pet</strong> increases physiological risk: older animals have less reserve to cope with hypoxia, stress and temperature changes in the hold. Cardiac, renal or metabolic compromise must be ruled out or stabilised before considering air transport. A simple health certificate is not enough; a thorough clinical and, where indicated, biochemical and imaging assessment is required.</p>\n<h2><span class=\"sec-label\">Section 1</span> Assessment and alternatives</h2>\n<p>Fit-to-fly assessment includes auscultation, blood pressure if indicated, renal and cardiac markers, and evaluation of stress tolerance. If the animal is not fit for cargo, cabin travel (where permitted), ground transport or postponement of the move should be considered. Zoovet Travel assesses geriatric patients in Trujillo and advises on the safest option for each case.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707 for a geriatric travel assessment.</p>",
        },
        "fr": {
            "title": "Voyager avec un animal gériatrique : risques et préparation",
            "description": "Guide technique vétérinaire sur le voyage international avec chien ou chat âgé : risque physiologique et évaluation fit-to-fly. Par la Dre Jessica Camacho.",
            "h1": "Voyager avec un animal gériatrique : risques et préparation",
            "body": "<p><strong>Voyager avec un animal gériatrique</strong> augmente le risque physiologique : les animaux âgés ont moins de réserve pour faire face à l'hypoxie, au stress et aux variations de température en soute. Une atteinte cardiaque, rénale ou métabolique doit être écartée ou stabilisée avant d'envisager le transport aérien. Un simple certificat de santé ne suffit pas ; un bilan clinique complet et, si indiqué, biochimique et d'imagerie est nécessaire.</p>\n<h2><span class=\"sec-label\">Section 1</span> Évaluation et alternatives</h2>\n<p>L'évaluation fit-to-fly inclut l'auscultation, la tension artérielle si indiquée, les marqueurs rénaux et cardiaques et l'évaluation de la tolérance au stress. Si l'animal n'est pas apte au cargo, le voyage en cabine (si autorisé), le transport terrestre ou le report du déménagement doivent être envisagés. Zoovet Travel évalue les patients gériatriques à Trujillo et conseille l'option la plus sûre pour chaque cas.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707 pour une évaluation voyage gériatrique.</p>",
        },
    },
    "requisitos_mascota_reino_unido_desde_latinoamerica_editorial_v2": {
        "en": {
            "title": "Requirements to take your pet to the United Kingdom from Latin America",
            "description": "Technical guide on UK pet import requirements from Latin America: microchip, vaccination, RNATT and official certificate. By Dr Jessica Camacho.",
            "h1": "Requirements to take your pet to the United Kingdom from Latin America",
            "body": "<p><strong>Requirements to take your pet to the United Kingdom</strong> from Latin America follow UK GOV and EU-derived rules. An ISO 11784/11785 FDX-B compliant microchip must be implanted before rabies vaccination. Rabies vaccination must be compliant with international movement regulations. A Rabies Neutralising Antibody Titration Test (RNATT) with result ≥ 0.5 IU/mL from an approved laboratory is required; the sample must be drawn at least 30 days after primary vaccination. An Official Veterinary Export Certificate endorsed by the exporting country is required, and treatment against Echinococcus multilocularis within the required window before entry.</p>\n<h2><span class=\"sec-label\">Section 1</span> Timeline and documentation</h2>\n<p>The process takes months: after the 30-day post-vaccination sample, laboratory turnaround, possible waiting period and travel. Any vaccination given before microchip implantation is invalid for UK purposes and restarts the protocol. Zoovet Travel manages the full chain from Trujillo for UK entry. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm current UK GOV requirements and build the calendar with a specialised veterinarian. Do not rely on outdated information.</p>",
        },
        "fr": {
            "title": "Conditions d'entrée d'un animal de compagnie au Royaume-Uni depuis l'Amérique latine",
            "description": "Guide technique sur les exigences d'importation au Royaume-Uni depuis l'Amérique latine : puce, vaccination, RNATT et certificat officiel. Par la Dre Jessica Camacho.",
            "h1": "Conditions d'entrée d'un animal de compagnie au Royaume-Uni depuis l'Amérique latine",
            "body": "<p>Les <strong>conditions d'entrée d'un animal de compagnie au Royaume-Uni</strong> depuis l'Amérique latine suivent les règles UK GOV et d'origine UE. Une puce conforme ISO 11784/11785 FDX-B doit être implantée avant la vaccination antirabique. La vaccination antirabique doit être conforme aux exigences réglementaires internationales. Un titrage sérologique des anticorps antirabiques (RNATT) avec résultat ≥ 0,5 UI/mL par un laboratoire approuvé est exigé ; le prélèvement doit être effectué au moins 30 jours après la primovaccination. Un certificat vétérinaire officiel d'exportation visé par le pays exportateur est requis, ainsi qu'un traitement contre Echinococcus multilocularis dans le délai exigé avant l'entrée.</p>\n<h2><span class=\"sec-label\">Section 1</span> Calendrier et documentation</h2>\n<p>Le processus prend des mois : après le prélèvement à 30 jours post-vaccination, le délai de laboratoire, une éventuelle période d'attente et le voyage. Toute vaccination faite avant l'implantation de la puce est invalide pour le Royaume-Uni et réinitialise le protocole. Zoovet Travel gère la chaîne complète depuis Trujillo pour l'entrée au Royaume-Uni. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez les exigences actuelles UK GOV et construisez le calendrier avec un vétérinaire spécialisé. Ne vous fiez pas à des informations obsolètes.</p>",
        },
    },
    "zoovet_canada_exportacion": {
        "en": {
            "title": "Exporting your pet to Canada: requirements and process",
            "description": "Technical guide on Canadian pet import requirements: CFIA rules, vaccination and official health certificate. By Dr Jessica Camacho, Zoovet Travel.",
            "h1": "Exporting your pet to Canada: requirements and process",
            "body": "<p><strong>Exporting your pet to Canada</strong> is governed by CFIA (Canadian Food Inspection Agency) requirements. Dogs and cats generally need a valid rabies vaccination and a health certificate issued by an authorised veterinarian and endorsed by the competent authority of the exporting country (e.g. SENASA for Peru). Some provinces or territories may have additional requirements; verification with the official CFIA portal and the destination province is mandatory.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentation and timing</h2>\n<p>Identification by ISO 11784/11785 compliant microchip is recommended or required depending on the province. The health certificate is usually valid for a limited period (e.g. 10 days or less). Zoovet Travel prepares the export file from Trujillo for Canada and coordinates with SENASA for official endorsement. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm current CFIA and provincial requirements before scheduling the certificate.</p>",
        },
        "fr": {
            "title": "Exporter son animal vers le Canada : exigences et démarches",
            "description": "Guide technique sur les exigences d'importation au Canada : règles de l'ACIA, vaccination et certificat de santé officiel. Par la Dre Jessica Camacho, Zoovet Travel.",
            "h1": "Exporter son animal vers le Canada : exigences et démarches",
            "body": "<p><strong>Exporter son animal vers le Canada</strong> est régi par les exigences de l'ACIA (Agence canadienne d'inspection des aliments). Les chiens et chats ont généralement besoin d'une vaccination antirabique en cours de validité et d'un certificat de santé délivré par un vétérinaire habilité et visé par l'autorité compétente du pays exportateur (ex. SENASA pour le Pérou). Certaines provinces ou territoires peuvent avoir des exigences supplémentaires ; la vérification auprès du portail officiel de l'ACIA et de la province de destination est obligatoire.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentation et délais</h2>\n<p>L'identification par puce conforme ISO 11784/11785 est recommandée ou exigée selon la province. Le certificat de santé est généralement valable pour une période limitée (ex. 10 jours ou moins). Zoovet Travel prépare le dossier d'exportation depuis Trujillo pour le Canada et coordonne avec le SENASA pour le visa officiel. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez les exigences actuelles de l'ACIA et provinciales avant de programmer le certificat.</p>",
        },
    },
    "bulldog_frances": {
        "en": {
            "title": "Travelling with a French Bulldog: brachycephalic risks and hold transport",
            "description": "Technical guide on travelling with French Bulldogs: BOAS risk in the aircraft hold and fit-to-fly assessment. By Dr Jessica Camacho.",
            "h1": "Travelling with a French Bulldog: brachycephalic risks and hold transport",
            "body": "<p><strong>Travelling with a French Bulldog</strong> in the aircraft hold carries high risk due to brachycephalic obstructive airway syndrome (BOAS). Reduced oxygen partial pressure at cruise altitude and stress can cause respiratory distress and collapse. Many airlines restrict or prohibit brachycephalic breeds in cargo. Cabin travel (where size allows) or alternative transport must be evaluated on a case-by-case basis.</p>\n<h2><span class=\"sec-label\">Section 1</span> Assessment and preparation</h2>\n<p>Cardiorespiratory assessment and, if indicated, imaging are essential. Sedation is contraindicated. The crate must be IATA LAR compliant. Zoovet Travel assesses French Bulldogs and other brachycephalic breeds in Trujillo and advises on the viability of air transport. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Schedule a fit-to-fly consultation before purchasing the ticket.</p>",
        },
        "fr": {
            "title": "Voyager avec un bouledogue français : risques brachycéphales et transport en soute",
            "description": "Guide technique sur le voyage avec bouledogue français : risque BOAS en soute et évaluation fit-to-fly. Par la Dre Jessica Camacho.",
            "h1": "Voyager avec un bouledogue français : risques brachycéphales et transport en soute",
            "body": "<p><strong>Voyager avec un bouledogue français</strong> en soute comporte un risque élevé en raison du syndrome obstructif des voies respiratoires des brachycéphales (BOAS). La baisse de pression partielle d'oxygène en croisière et le stress peuvent provoquer détresse respiratoire et collapsus. De nombreuses compagnies restreignent ou interdisent les races brachycéphales en cargo. Le voyage en cabine (si la taille le permet) ou un transport alternatif doit être évalué au cas par cas.</p>\n<h2><span class=\"sec-label\">Section 1</span> Évaluation et préparation</h2>\n<p>Un bilan cardiorespiratoire et, si indiqué, une imagerie sont indispensables. La sédation est contre-indiquée. La caisse doit être conforme IATA LAR. Zoovet Travel évalue les bouledogues français et autres races brachycéphales à Trujillo et conseille sur la viabilité du transport aérien. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Prenez rendez-vous pour une consultation fit-to-fly avant d'acheter le billet.</p>",
        },
    },
    "como_viajar_perro_espana_desde_peru_requisitos_final_v2": {
        "en": {
            "title": "How to travel to Spain with your dog from Peru: requirements",
            "description": "Technical guide on Spanish pet import requirements from Peru: EU Regulation 576/2013, microchip, vaccination and health certificate. By Dr Jessica Camacho.",
            "h1": "How to travel to Spain with your dog from Peru: requirements",
            "body": "<p><strong>Requirements to travel to Spain with your dog from Peru</strong> follow EU Regulation 576/2013 and Spanish implementation. An ISO 11784/11785 compliant microchip, rabies vaccination valid for at least 21 days after primary vaccination (or within validity if revaccinated), and an Official Veterinary Export Certificate issued and endorsed within the required validity (usually 10 days or less) are standard. Treatment against Echinococcus multilocularis within the required window is mandatory for Spain.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentation and timing</h2>\n<p>The health certificate must be issued by an authorised veterinarian and endorsed by the competent authority (e.g. SENASA for Peru). Zoovet Travel manages the full chain from Trujillo for Spain. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm current requirements with the official Spanish and EU sources before scheduling.</p>",
        },
        "fr": {
            "title": "Comment voyager en Espagne avec son chien depuis le Pérou : exigences",
            "description": "Guide technique sur les exigences d'importation en Espagne depuis le Pérou : Règlement UE 576/2013, puce, vaccination et certificat de santé. Par la Dre Jessica Camacho.",
            "h1": "Comment voyager en Espagne avec son chien depuis le Pérou : exigences",
            "body": "<p>Les <strong>conditions pour voyager en Espagne avec son chien depuis le Pérou</strong> suivent le Règlement UE 576/2013 et la transposition espagnole. Une puce conforme ISO 11784/11785, une vaccination antirabique valable au moins 21 jours après la primovaccination (ou dans la validité en cas de revaccination), et un certificat vétérinaire officiel d'exportation délivré et visé dans le délai de validité exigé (généralement 10 jours ou moins) sont la norme. Le traitement contre Echinococcus multilocularis dans le délai exigé est obligatoire pour l'Espagne.</p>\n<h2><span class=\"sec-label\">Section 1</span> Documentation et délais</h2>\n<p>Le certificat de santé doit être délivré par un vétérinaire habilité et visé par l'autorité compétente (ex. SENASA pour le Pérou). Zoovet Travel gère la chaîne complète depuis Trujillo pour l'Espagne. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez les exigences en vigueur auprès des sources officielles espagnoles et européennes avant de programmer.</p>",
        },
    },
    "queeselmicrochipdondelotramitas": {
        "en": {
            "title": "What is the microchip and where to get it for pet travel",
            "description": "Technical guide on the ISO 11784/11785 microchip for international pet travel: identification and where to have it implanted. By Dr Jessica Camacho.",
            "h1": "What is the microchip and where to get it for pet travel",
            "body": "<p>The <strong>microchip for pet travel</strong> is an ISO 11784/11785 FDX-B compliant transponder implanted subcutaneously, which allows unique identification of the animal. For international movement it is not optional: it is the health identity that links the animal to vaccination acts and laboratory results. In destinations such as the United Kingdom, Australia or Japan, rabies vaccination administered before microchip implantation is invalid and restarts the entire protocol.</p>\n<h2><span class=\"sec-label\">Section 1</span> Where to have it implanted and timing</h2>\n<p>The microchip must be implanted before the first rabies vaccination in the export process. It must be read at the official inspection and appear on all certificates. In Trujillo, Zoovet Travel implants compliant microchips and integrates them into the export file from the start. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Do not vaccinate before implanting the microchip if your destination requires traceability; otherwise the vaccination will not count.</p>",
        },
        "fr": {
            "title": "Qu'est-ce que la puce et où la faire poser pour voyager avec son animal",
            "description": "Guide technique sur la puce ISO 11784/11785 pour le voyage international avec animal : identification et où la faire poser. Par la Dre Jessica Camacho.",
            "h1": "Qu'est-ce que la puce et où la faire poser pour voyager avec son animal",
            "body": "<p>La <strong>puce pour voyager avec son animal</strong> est un transpondeur conforme ISO 11784/11785 FDX-B implanté en sous-cutané, qui permet l'identification unique de l'animal. Pour le mouvement international elle n'est pas optionnelle : c'est l'identité sanitaire qui lie l'animal aux actes vaccinaux et aux résultats de laboratoire. Pour des destinations comme le Royaume-Uni, l'Australie ou le Japon, une vaccination antirabique administrée avant l'implantation de la puce est invalide et réinitialise tout le protocole.</p>\n<h2><span class=\"sec-label\">Section 1</span> Où la faire poser et délais</h2>\n<p>La puce doit être implantée avant la première vaccination antirabique du processus d'exportation. Elle doit être lue lors de l'inspection officielle et figurer sur tous les certificats. À Trujillo, Zoovet Travel pose des puces conformes et les intègre au dossier d'exportation dès le départ. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Ne vaccinez pas avant d'implanter la puce si votre destination exige la traçabilité ; sinon la vaccination ne comptera pas.</p>",
        },
    },
    "rnattviajes": {
        "en": {
            "title": "Rabies Antibody Titration Test (RNATT) for pet travel",
            "description": "Technical guide on the RNATT: what it is, when the sample is taken (30 days after vaccination), and which destinations require it. By Dr Jessica Camacho.",
            "h1": "Rabies Antibody Titration Test (RNATT) for pet travel",
            "body": "<p>The <strong>Rabies Neutralising Antibody Titration Test (RNATT)</strong> measures the level of neutralising antibodies against rabies in the blood, usually reported in IU/mL (RFFIT or FAVN). Many high-surveillance destinations (United Kingdom, Australia, Japan, United States from high-risk countries, etc.) require a result ≥ 0.5 IU/mL. The blood sample must be drawn at least 30 days after primary rabies vaccination; a sample taken before day 30 is not legally admissible in the EU and equivalent frameworks, even if the titre is high.</p>\n<h2><span class=\"sec-label\">Section 1</span> Laboratory and timeline</h2>\n<p>The sample must be sent to an OIE-accredited or approved laboratory. Turnaround time and possible waiting periods at destination extend the total process to months. Planning the vaccination date in reverse from the intended departure date is essential. Zoovet Travel manages sampling and international shipment from Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Confirm whether your destination requires RNATT and build the calendar from day 30 post-vaccination.</p>",
        },
        "fr": {
            "title": "Titrage sérologique des anticorps antirabiques (RNATT) pour voyager avec son animal",
            "description": "Guide technique sur le RNATT : ce que c'est, quand faire le prélèvement (30 jours après la vaccination) et quelles destinations l'exigent. Par la Dre Jessica Camacho.",
            "h1": "Titrage sérologique des anticorps antirabiques (RNATT) pour voyager avec son animal",
            "body": "<p>Le <strong>titrage sérologique des anticorps antirabiques (RNATT)</strong> mesure le taux d'anticorps neutralisants contre la rage dans le sang, généralement rapporté en UI/mL (RFFIT ou FAVN). De nombreuses destinations à haute surveillance (Royaume-Uni, Australie, Japon, États-Unis depuis pays à haut risque, etc.) exigent un résultat ≥ 0,5 UI/mL. Le prélèvement sanguin doit être effectué au moins 30 jours après la primovaccination antirabique ; un prélèvement avant le jour 30 n'est pas juridiquement recevable dans l'UE et cadres équivalents, même si le titre est élevé.</p>\n<h2><span class=\"sec-label\">Section 1</span> Laboratoire et calendrier</h2>\n<p>L'échantillon doit être envoyé à un laboratoire accrédité OIE ou approuvé. Le délai de traitement et d'éventuelles périodes d'attente à la destination prolongent le processus total à des mois. Planifier la date de vaccination à l'envers à partir de la date de départ prévue est indispensable. Zoovet Travel gère le prélèvement et l'envoi international depuis Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Confirmez si votre destination exige le RNATT et construisez le calendrier à partir du jour 30 post-vaccination.</p>",
        },
    },
    "articulo_golden_labrador_cabina_bodega": {
        "en": {
            "title": "Golden Retriever and Labrador: cabin or hold? Size and airline rules",
            "description": "Technical guide on whether large breeds such as Golden Retriever and Labrador can travel in the cabin or must go in the hold. By Dr Jessica Camacho.",
            "h1": "Golden Retriever and Labrador: cabin or hold? Size and airline rules",
            "body": "<p>Whether a <strong>Golden Retriever or Labrador</strong> travels in the cabin or in the hold depends on the airline's size and weight limits for cabin travel. Most commercial airlines only allow small pets in the cabin (carrier under the seat); dogs of this size normally travel in the hold in an IATA LAR-compliant crate. Both options require the same documentary chain (microchip, vaccination, official certificate); the difference is the physiological risk and the need for a fit-to-fly assessment for hold travel.</p>\n<h2><span class=\"sec-label\">Section 1</span> Hold travel and preparation</h2>\n<p>Large breeds in the hold need adequate crate size, conditioning to the crate and a health assessment to rule out cardiac or respiratory compromise. Zoovet Travel assesses fitness for hold travel and prepares the export file from Trujillo. Contact us at 044 366094 or WhatsApp +51 979 620 402 and +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> What to resolve before starting</h2>\n<p>Check the airline's current cabin size and weight limits and hold restrictions before booking.</p>",
        },
        "fr": {
            "title": "Golden Retriever et Labrador : cabine ou soute ? Taille et règles des compagnies",
            "description": "Guide technique sur la possibilité pour les grandes races (Golden Retriever, Labrador) de voyager en cabine ou en soute. Par la Dre Jessica Camacho.",
            "h1": "Golden Retriever et Labrador : cabine ou soute ? Taille et règles des compagnies",
            "body": "<p>Qu'un <strong>Golden Retriever ou Labrador</strong> voyage en cabine ou en soute dépend des limites de taille et de poids en cabine de la compagnie. La plupart des compagnies commerciales n'autorisent en cabine que les petits animaux (transport sous le siège) ; les chiens de cette taille voyagent normalement en soute dans une caisse conforme IATA LAR. Les deux options exigent la même chaîne documentaire (puce, vaccination, certificat officiel) ; la différence est le risque physiologique et la nécessité d'une évaluation fit-to-fly pour le voyage en soute.</p>\n<h2><span class=\"sec-label\">Section 1</span> Voyage en soute et préparation</h2>\n<p>Les grandes races en soute ont besoin d'une caisse de taille adéquate, d'une familiarisation à la caisse et d'un bilan de santé pour écarter une atteinte cardiaque ou respiratoire. Zoovet Travel évalue l'aptitude au voyage en soute et prépare le dossier d'exportation depuis Trujillo. Contactez-nous au 044 366094 ou par WhatsApp +51 979 620 402 et +51 922 083 707.</p>\n<h2><span class=\"sec-label\">Section 2</span> Ce qu'il convient de régler avant de commencer</h2>\n<p>Vérifiez les limites actuelles de taille et de poids en cabine et les restrictions en soute de la compagnie avant de réserver.</p>",
        },
    },
}
