# -*- coding: utf-8 -*-
# V5 — Full professional EN/FR translations. One title only (no duplicate | Zoovet Travel).
# Body: Section 1, Section 2... in EN; Section 1, Section 2... in FR.

def _sec(en_label, en_title, fr_title, en_paras, fr_paras):
    en = f'<h2><span class="sec-label">{en_label}</span> {en_title}</h2>\n' + "\n".join(f"<p>{p}</p>" for p in en_paras)
    fr = f'<h2><span class="sec-label">{en_label}</span> {fr_title}</h2>\n' + "\n".join(f"<p>{p}</p>" for p in fr_paras)
    return en, fr


TRANSLATIONS = {
    "articulo_alimentacion_antes_durante_vuelo": {
        "en": {
            "title": "Feeding before and during flight: fasting, water and errors that cause vomiting",
            "description": "Clinical guide for feeding dogs and cats before and during a flight: food and water windows, what to avoid, and how to manage layovers without decompensation.",
            "h1": "Feeding before and during flight: what to give and what to avoid",
            "body": """<p>In-flight vomiting rarely originates in the aircraft. It originates in the wrong breakfast and in the anxiety of &ldquo;not letting them go hungry.&rdquo; When that vomiting occurs inside the kennel, the animal gets dirty, cold, stressed and arrives at destination with an irritated digestive system.</p>
<p>In practice in Trujillo, Peru, the most repeated error is changing the routine on the day of travel. <strong>Feeding before and during flight</strong> works when it is conservative: less variation, less volume, more control of timing.</p>
<h2><span class="sec-label">Section 1</span> Why overfeeding before flying becomes a problem</h2>
<p>Cabin pressure is lower than at sea level. That hypobaria changes bodily perception: abdominal distension, nausea and increased gas become more likely, especially in anxious animals. If the stomach is full, the probability of regurgitation or vomiting increases without any underlying disease.</p>
<p>Stress also plays a role. The animal arrives at the airport with noise, new smells, temperature changes and hours of waiting. In that context, gastric emptying slows. Food that digests uneventfully at home can remain in the stomach longer and become vomitable content during boarding.</p>
<p>Many owners interpret food as a calming agent. In clinic we see the opposite: increased food volume on a day of stress increases digestive events. The operational detail is set out in <a href="../articles/zoovet_art5_estres-metabolico-EN.html">Metabolic stress in flight: why some dogs decompensate without being ill</a> because it is not about hunger; it is about physiological tolerance under stress.</p>
<h2><span class="sec-label">Section 2</span> Before flight: food and water window that works in practice</h2>
<p>In a healthy adult, the last full meal usually works best if it occurs 6 to 8 hours before boarding. That window reduces gastric volume without causing a sharp drop in energy in most dogs and cats. When the flight departs early, the cleanest adjustment is to bring forward the previous day&rsquo;s dinner, not to force an early breakfast. In that window, feeding before and during flight reduces incidents during boarding.</p>
<p>A small snack 3 to 4 hours before can be useful if the animal tends to bile from prolonged fasting. Small means small: a fraction of their usual ration, not a new meal. When used, the criterion is not &ldquo;so they eat something,&rdquo; it is to avoid an overly empty stomach in an animal that acidifies easily.</p>
<p>Water is managed differently. Withholding it from the night before causes dehydration and intense thirst, which increases panting and anxiety. In most cases, water can remain available until leaving home and then be offered in small amounts during the wait. In Trujillo, Peru, the typical scene is an animal that arrives at the airport thirsty because &ldquo;they couldn&rsquo;t drink anything,&rdquo; and that thirst ends in rapid intakes that also favour vomiting.</p>
<h2><span class="sec-label">Section 3</span> During flight and on layovers: control volume, do not improvise diet</h2>
<p>On short flights, the best strategy is usually not to give food during the journey. The aim is to avoid the nausea–vomiting–food refusal cycle. If the animal travels in hold, there is also no direct supervision and any episode becomes clinically more costly.</p>
<p>On long layovers, the risk changes. The key is to keep the known diet and fractionate. A minimal portion of the usual food, offered when the animal is already calm, tends to be tolerated better than random snacks. What is not anticipated is that diarrhoea from new food in transit can trigger additional controls and complicate hygienic handling logistics.</p>
<p>Water during layovers should be frequent and in small amounts. If a full bowl is offered to an excited animal, many drink quickly and swallow air. That translates into distension and regurgitation. A simple approach that works is to offer sips, wait, and repeat, instead of a single large intake.</p>
<h2><span class="sec-label">Section 4</span> What to give and what to avoid without falling into recipes</h2>
<p>What to give: the usual diet. If the animal eats kibble, keep the same. If they eat a home-prepared diet, keep the same composition. The journey is not the day to &ldquo;improve&rdquo; feeding. The digestive system rewards stability, not intention.</p>
<p>What to avoid: fatty food, excessive treats, dairy if not usually part of the diet, recreational bones, and any new food &ldquo;to make them feel better.&rdquo; It is also advisable to avoid large portions just before departure, even with known foods, because volume is the factor that correlates most with vomiting.</p>
<p>In cats, post-stress food refusal appears more often than in dogs. Forcing food in an anxious cat usually worsens the picture. A conservative approach is to prioritise hydration and allow them to resume their diet when the environment is stable.</p>
<h2><span class="sec-label">Section 5</span> What to resolve before starting</h2>
<p>Define the real door-to-door duration, not just flight hours. A 4-hour journey can become 10 if you add transfer, check-in, waiting and layover. The feeding plan is built on that total, because the animal&rsquo;s tolerance is measured in hours of continuous stress.</p>
<p>Review the animal&rsquo;s digestive history with clinical honesty. A dog with motion-related vomiting or a cat that stops eating under stress is not managed like a stable animal. In those cases, <strong>feeding before and during flight</strong> requires adjusting volume and timing with your primary veterinarian, because some animals do not tolerate long fasts and others do not tolerate snacks.</p>
<p>Prepare the kennel as a feeding scenario. A fixed water container reduces spillage. If travelling with a blanket, avoid fabrics that soak easily and cool. When vomiting or diarrhoea occurs, the difference between control and chaos is often environmental management, not the food itself.</p>
<p>Decide what you will do in case of delay. Delays change windows and push feeding into a noisy, crowded place. A written plan of minimal portions and fractionated water avoids impulsive decisions at the counter. When logistics tighten, a conservative plan holds up better than improvisation.</p>
<!-- CTA-START -->
<p>A digestive episode in flight can turn a simple transfer into an arrival with dehydration, cold and complex hygienic handling. Zoovet Travel reviews the clinical case and designs a feeding plan before and during flight integrated with the itinerary and type of transport from Trujillo, Peru. Contact +51 979 620 402 — +51 922 083 707 — 044 366094. The difference often lies in controlling volume and timing before the airport controls the rest.</p>
<!-- CTA-END -->""",
        },
        "fr": {
            "title": "Alimentation avant et pendant le vol : jeûne, eau et erreurs à l'origine des vomissements",
            "description": "Guide clinique pour alimenter chiens et chats avant et pendant un vol : fenêtres alimentation et eau, à éviter, et gestion des escales sans décompensation.",
            "h1": "Alimentation avant et pendant le vol : quoi donner et quoi éviter",
            "body": """<p>Le vomissement en vol naît rarement dans l&rsquo;avion. Il naît du mauvais petit-déjeuner et de l&rsquo;anxiété de &ldquo;ne pas les laisser avoir faim&rdquo;. Lorsque ce vomissement survient dans la cage, l&rsquo;animal se salit, se refroidit, se stresse et arrive à destination avec un système digestif irrité.</p>
<p>En consultation à Trujillo, Pérou, l&rsquo;erreur la plus répétée est de changer la routine le jour du voyage. <strong>L&rsquo;alimentation avant et pendant le vol</strong> fonctionne lorsqu&rsquo;elle est conservative : moins de variation, moins de volume, plus de maîtrise des horaires.</p>
<h2><span class="sec-label">Section 1</span> Pourquoi manger trop avant le vol devient un problème</h2>
<p>En cabine, la pression est inférieure au niveau de la mer. Cette hypobarie modifie la perception corporelle : distension abdominale, nausée et augmentation des gaz deviennent plus probables, surtout chez les animaux anxieux. Si l&rsquo;estomac est plein, la probabilité de régurgitation ou vomissement augmente sans maladie sous-jacente.</p>
<p>Le stress joue aussi. L&rsquo;animal arrive à l&rsquo;aéroport avec le bruit, les odeurs nouvelles, les changements de température et les heures d&rsquo;attente. Dans ce contexte, la vidange gastrique ralentit. La nourriture digérée sans problème à la maison peut rester plus longtemps dans l&rsquo;estomac et devenir un contenu vomissable à l&rsquo;embarquement.</p>
<p>Beaucoup de propriétaires considèrent la nourriture comme un calmant. En clinique, c&rsquo;est l&rsquo;inverse : l&rsquo;augmentation du volume alimentaire un jour de stress augmente les événements digestifs. Le détail opérationnel est développé dans <a href="../articles/zoovet_art5_estres-metabolico-FR.html">Stress métabolique en vol : pourquoi certains chiens se décompensent sans être malades</a>, car il ne s&rsquo;agit pas de faim mais de tolérance physiologique sous stress.</p>
<h2><span class="sec-label">Section 2</span> Avant le vol : fenêtre alimentation et eau qui fonctionne en pratique</h2>
<p>Chez un adulte sain, le dernier repas complet fonctionne souvent mieux s&rsquo;il a lieu 6 à 8 heures avant l&rsquo;embarquement. Cette fenêtre réduit le volume gastrique sans chute brutale d&rsquo;énergie chez la plupart des chiens et chats. Quand le vol part tôt, l&rsquo;ajustement le plus propre est d&rsquo;avancer le dîner de la veille, pas de forcer un petit-déjeuner tôt. Dans cette fenêtre, l&rsquo;alimentation avant et pendant le vol réduit les incidents à l&rsquo;embarquement.</p>
<p>Une petite collation 3 à 4 heures avant peut être utile si l&rsquo;animal tend à la bile par jeûne prolongé. Petite signifie petite : une fraction de sa ration habituelle, pas un nouveau repas. Quand on l&rsquo;utilise, le critère n&rsquo;est pas &ldquo;qu&rsquo;il mange quelque chose&rdquo;, c&rsquo;est d&rsquo;éviter un estomac trop vide chez un animal qui s&rsquo;acidifie facilement.</p>
<p>L&rsquo;eau se gère autrement. La retirer depuis la veille au soir provoque déshydratation et soif intense, ce qui augmente halètement et anxiété. Dans la plupart des cas, l&rsquo;eau peut rester disponible jusqu&rsquo;au départ du domicile puis être proposée en petites quantités pendant l&rsquo;attente. À Trujillo, Pérou, la scène typique est un animal qui arrive à l&rsquo;aéroport assoiffé parce que &ldquo;il ne pouvait rien boire&rdquo;, et cette soif se termine en prises rapides qui favorisent aussi le vomissement.</p>
<h2><span class="sec-label">Section 3</span> Pendant le vol et en escale : maîtriser le volume, ne pas improviser l&rsquo;alimentation</h2>
<p>Sur les vols courts, la meilleure stratégie est souvent de ne pas donner à manger pendant le trajet. L&rsquo;objectif est d&rsquo;éviter le cycle nausée–vomissement–refus alimentaire. Si l&rsquo;animal voyage en soute, il n&rsquo;y a pas de surveillance directe et tout épisode devient cliniquement plus coûteux.</p>
<p>En escales longues, le risque change. La clé est de conserver l&rsquo;alimentation connue et fractionner. Une portion minimale de l&rsquo;aliment habituel, proposée quand l&rsquo;animal est déjà calmé, tend à être mieux tolérée que des snacks aléatoires. Ce qu&rsquo;on n&rsquo;anticipe pas, c&rsquo;est qu&rsquo;une diarrhée par nourriture nouvelle en transit peut activer des contrôles supplémentaires et compliquer la logistique d&rsquo;hygiène.</p>
<p>L&rsquo;eau en escale doit être fréquente et en petite quantité. Si on propose un bol complet à un animal excité, beaucoup boivent vite et avalent de l&rsquo;air. Cela se traduit par distension et régurgitation. Une règle simple qui fonctionne : proposer des gorgées, attendre, répéter, plutôt qu&rsquo;une seule prise importante.</p>
<h2><span class="sec-label">Section 4</span> Quoi donner et quoi éviter sans tomber dans les recettes</h2>
<p>Quoi donner : l&rsquo;alimentation habituelle. Si l&rsquo;animal mange des croquettes, garder les mêmes. S&rsquo;il mange une ration ménagère, garder la même composition. Le voyage n&rsquo;est pas le jour pour &ldquo;améliorer&rdquo; l&rsquo;alimentation. Le système digestif ne récompense pas l&rsquo;intention, il récompense la stabilité.</p>
<p>Quoi éviter : nourriture grasse, friandises en excès, laitages s&rsquo;ils ne font pas partie de l&rsquo;habitude, os récréatifs, et tout aliment nouveau &ldquo;pour qu&rsquo;il se sente mieux&rdquo;. Il convient aussi d&rsquo;éviter les grandes portions juste avant le départ, même avec des aliments connus, car le volume est le facteur qui corrèle le plus avec le vomissement.</p>
<p>Chez le chat, le refus alimentaire post-stress apparaît plus souvent que chez le chien. Forcer la nourriture chez un chat anxieux aggrave souvent le tableau. Une approche conservative est de prioriser l&rsquo;hydratation et permettre la reprise de l&rsquo;alimentation quand l&rsquo;environnement est stable.</p>
<h2><span class="sec-label">Section 5</span> Ce qu&rsquo;il convient de régler avant de commencer</h2>
<p>Définir la durée réelle porte à porte, pas seulement les heures de vol. Un trajet de 4 heures peut en faire 10 si on ajoute transfert, enregistrement, attente et escale. Le plan d&rsquo;alimentation se construit sur ce total, car la tolérance de l&rsquo;animal se mesure en heures de stress continu.</p>
<p>Revoir l&rsquo;historique digestif de l&rsquo;animal avec honnêteté clinique. Un chien avec vomissements au transport ou un chat qui cesse de manger sous stress ne se gère pas comme un animal stable. Dans ces cas, <strong>l&rsquo;alimentation avant et pendant le vol</strong> nécessite d&rsquo;ajuster volume et timing avec le vétérinaire traitant, car certains animaux ne tolèrent pas les jeûnes longs et d&rsquo;autres pas les collations.</p>
<p>Préparer la cage comme scénario alimentaire. Un récipient fixe pour l&rsquo;eau réduit les fuites. S&rsquo;il voyage avec une couverture, éviter les tissus qui se trempent facilement et refroidissent. En cas de vomissement ou diarrhée, la différence entre maîtrise et chaos tient souvent à la gestion de l&rsquo;environnement, pas à la nourriture elle-même.</p>
<p>Décider quoi faire en cas de retard. Les retards déplacent les fenêtres et poussent à nourrir dans un lieu bruyant et saturé. Un plan écrit de portions minimales et d&rsquo;eau fractionnée évite les décisions impulsives au comptoir. Quand la logistique se tend, un plan conservateur tient mieux qu&rsquo;une improvisation.</p>
<!-- CTA-START -->
<p>Un épisode digestif en vol peut transformer un simple transfert en arrivée avec déshydratation, froid et gestion hygiénique complexe. Zoovet Travel examine le cas clinique et conçoit une conduite alimentaire avant et pendant le vol intégrée à l&rsquo;itinéraire et au type de transport depuis Trujillo, Pérou. Contacter le +51 979 620 402 — +51 922 083 707 — 044 366094. La différence tient souvent au contrôle du volume et des horaires avant que l&rsquo;aéroport ne contrôle le reste.</p>
<!-- CTA-END -->""",
        },
    },
    "streesmascotas": {
        "en": {
            "title": "Signs of stress in your pet during travel and what to do",
            "description": "Clinical analysis by Dr Jessica Camacho on signs of stress in your pet during travel and technical intervention protocols for international flights.",
            "h1": "Signs of stress in your pet during travel and what to do",
            "body": """<p>Collapse of the neuroendocrine system in a confined animal does not manifest only through crying or escape attempts, but through silent metabolic alterations that compromise survival. Recognising <strong>signs of stress in your pet during travel and what to do</strong> about them separates a successful arrival from a clinical emergency at the destination airport. In Trujillo we see patients that arrive with severe dehydration because their owners did not interpret that persistent panting was not heat but a cortisol storm.</p>
<h2><span class="sec-label">Section 1</span> The physiology of fear and HPA axis activation</h2>
<p>Exposure to turbine noise, vibrations and atmospheric pressure changes triggers immediate release of catecholamines and glucocorticoids from the adrenal glands into the bloodstream. This response, mediated by the hypothalamic–pituitary–adrenal (HPA) axis, causes increased heart rate, hypertension and redistribution of blood flow away from the digestive system to prioritise muscles. If the pet shows mydriasis (dilated pupils), hypersalivation or fine muscle tremors, the organism has already exceeded its initial compensation capacity and entered a phase of acute distress.</p>
<p>Desynchronisation of biological rhythms weakens the intestinal barrier, allowing opportunistic bacteria to cross the mucosa and generate a systemic inflammatory response before landing. The molecular mechanisms of this vulnerability are detailed in our study on <a href="../articles/zoovet_art5_estres-metabolico-EN.html">The gut–brain axis in dogs and cats during international transport: neuroendocrine integration, microbiota and energy metabolism</a>. A dog that yawns repeatedly or shows &ldquo;whale eye&rdquo; (sclera visible) is communicating an anxiety level that precedes total metabolic exhaustion.</p>
<h2><span class="sec-label">Section 2</span> Clinical manifestations of stress in cats</h2>
<p>Felines manage stress through behavioural inhibition, which is often mistaken for calm when it is actually tonic immobility induced by panic. A cat that travels in silence but has shallow rapid breathing or sweaty footpads is suffering severe neurovegetative impact. Feline hepatic lipidosis is the most serious consequence; a cat that refuses to eat for more than 24 hours due to fear starts massive mobilisation of fat to the liver that can be lethal.</p>
<p>Facial marking and synthetic pheromones help reduce central nervous system reactivity but do not replace prior carrier conditioning. What people do not anticipate is that a cat that grooms excessively (stress grooming) or hides at the back of the carrier is trying to regulate a core temperature that rises dangerously with anxiety. Intervention at this point requires thermal stabilisation and avoiding unnecessary handling that increases perceived threat in the airport terminal environment.</p>
<h2><span class="sec-label">Section 3</span> Intervention protocols and what to do in transit</h2>
<p>Technical hydration is the most powerful defence tool against the blood viscosity caused by constant adrenaline release. Providing fresh water via drip drinkers allows the pet to keep mucous membranes moist without spillage risk that wets the coat and causes evaporative hypothermia in the cabin. If you notice your dog panting stridently, apply cool cloths to sparsely haired areas such as the inguinal region to force a drop in core temperature before a heat-stroke denial of boarding.</p>
<p>Administration of nutritional supplements containing L-theanine or alpha-casozepine, started at least seven days before export, helps modulate GABA receptors without the dangerous sedation that airlines prohibit. These substances allow the animal to process external stimuli without entering a panic cycle leading to self-injury inside the crate. When detecting signs of stress in your pet during travel and what to do, the priority must be reducing visual stimuli by partially covering the carrier with a blanket that preserves ventilation but removes the chaotic movement of the airport.</p>
<h2><span class="sec-label">Section 4</span> What to resolve before starting</h2>
<p>Acclimatisation to the carrier is a process that takes on average eight weeks of positive training for the animal to identify it as a biological safety zone. Putting a pet into a new carrier on the day of the flight guarantees an uncontrollable stress response that will raise blood glucose and lactate. In our clinic in Peru we assess the patient&rsquo;s baseline heart rate inside their travel crate to issue a health certificate with a real fitness criterion, not a purely administrative one.</p>
<p>The pre-export clinical examination must include dental and pad review, as chronic stress exacerbates any pre-existing inflammatory focus. SENASA requires the animal to be free of ectoparasites and in good general condition, but a professional must go further and verify cardiovascular stability under effort. A dog with subclinical heart murmurs will fail much sooner under the mild hypoxia of flight if boarding stress has already exhausted myocardial oxygen reserve.</p>
<p>Internal parasite treatment must use drugs without emetic side effects, as a vomiting episode in the carrier increases aspiration pneumonia risk. Active ingredient choice must align with the destination country&rsquo;s regulatory windows, such as treatment against Echinococcus multilocularis required by the United Kingdom or Norway between 24 and 120 hours before entry. An error in this time window not only creates a documentary problem but forces repeat veterinary handling that stresses the animal just before their longest flight.</p>
<p>Misreading your pet&rsquo;s physiological state can lead to multiorgan failure or sudden death during international transport. Zoovet Travel audits the neuroendocrine stability of patients in Trujillo to mitigate signs of stress in your pet during travel and what to do to prevent them. Schedule your technical consultation at +51 979 620 402 or +51 922 083 707 to validate your companion&rsquo;s travel protocol. Ensure a healthy landing with specialised clinical support.</p>""",
        },
        "fr": {
            "title": "Signes de stress chez votre animal pendant le voyage et que faire",
            "description": "Analyse clinique de la Dre Jessica Camacho sur les signes de stress chez votre animal pendant le voyage et protocoles d'intervention technique pour les vols internationaux.",
            "h1": "Signes de stress chez votre animal pendant le voyage et que faire",
            "body": """<p>L'effondrement du système neuroendocrinien chez un animal confiné ne se manifeste pas seulement par des pleurs ou des tentatives d'évasion, mais par des altérations métaboliques silencieuses qui compromettent sa survie. Reconnaître les <strong>signes de stress chez votre animal pendant le voyage et que faire</strong> permet de distinguer une arrivée réussie d'une urgence clinique à l'aéroport de destination. À Trujillo, nous recevons des patients en déshydratation sévère parce que leurs propriétaires n'ont pas su interpréter que le halètement persistant n'était pas la chaleur mais une tempête de cortisol.</p>
<h2><span class="sec-label">Section 1</span> Physiologie de la peur et activation de l'axe HPA</h2>
<p>L'exposition aux bruits de turbines, vibrations et changements de pression atmosphérique déclenche la libération immédiate de catécholamines et glucocorticoides des glandes surrénales vers le sang. Cette réponse, médiée par l'axe hypothalamo-hypophyso-surrénalien (HPA), provoque augmentation de la fréquence cardiaque, hypertension et redistribution du flux sanguin qui quitte le système digestif pour prioriser les muscles. Si l'animal présente mydriase, hypersalivation ou tremblements musculaires fins, l'organisme a dépassé sa capacité de compensation initiale et est entré en phase de détresse aiguë.</p>
<p>La désynchronisation des rythmes biologiques fragilise la barrière intestinale, permettant à des bactéries opportunistes de traverser la muqueuse et de générer une réponse inflammatoire systémique avant l'atterrissage. Les mécanismes moléculaires de cette vulnérabilité sont détaillés dans notre étude sur <a href="../articles/zoovet_art5_estres-metabolico-FR.html">L'axe intestin–cerveau chez le chien et le chat lors du transport international</a>. Un chien qui bâille de façon répétée ou présente un &ldquo;œil de baleine&rdquo; (sclérotique visible) communique un niveau d'anxiété qui précède l'épuisement métabolique total.</p>
<h2><span class="sec-label">Section 2</span> Manifestations cliniques du stress chez le chat</h2>
<p>Les félins gèrent le stress par l'inhibition comportementale, souvent confondue avec le calme alors qu'il s'agit d'une immobilité tonique induite par la panique. Un chat qui voyage en silence mais garde une respiration superficielle et rapide, ou des coussinets plantaires en sueur, subit un impact neurovégétatif sévère. La lipidose hépatique féline en est la conséquence la plus grave ; un chat qui refuse de manger plus de 24 h par peur déclenche une mobilisation massive des graisses vers le foie pouvant être létale.</p>
<p>Le marquage facial et les phéromones de synthèse aident à réduire la réactivité du système nerveux central mais ne remplacent pas le conditionnement préalable au transport. Ce que les gens n'anticiperont pas : un chat qui se lèche excessivement (toilettage de stress) ou se cache au fond du transport cherche à réguler une température interne qui monte dangereusement avec l'anxiété. Intervenir à ce stade nécessite stabilisation thermique et évitement des manipulations inutiles qui augmentent la perception de menace dans l'environnement de l'aéroport.</p>
<h2><span class="sec-label">Section 3</span> Protocoles d'intervention et que faire en transit</h2>
<p>L'hydratation technique est l'outil de défense le plus puissant face à la viscosité sanguine provoquée par la libération constante d'adrénaline. Proposer de l'eau fraîche via des abreuvoirs à goutte permet à l'animal de garder les muqueuses humides sans risque de fuites qui mouillent le pelage et provoquent une hypothermie par évaporation en cabine. Si vous constatez que votre chien halète de façon striduleuse, appliquer des linges frais sur les zones peu poilues (région inguinale) pour faire baisser la température interne avant un refus d'embarquement pour suspicion de coup de chaleur.</p>
<p>L'administration de compléments contenant L-théanine ou alpha-casozépine, commencée au moins sept jours avant l'exportation, aide à moduler les récepteurs GABA sans sédation dangereuse interdite par les compagnies. Ces substances permettent à l'animal de traiter les stimuli externes sans entrer dans un cycle de panique menant à des auto-mutilations dans la cage. Face aux signes de stress chez votre animal pendant le voyage et que faire, la priorité doit être la réduction des stimuli visuels en couvrant partiellement le transport avec une couverture qui conserve la ventilation mais supprime le mouvement chaotique de l'aéroport.</p>
<h2><span class="sec-label">Section 4</span> Ce qu'il convient de régler avant de commencer</h2>
<p>L'acclimatation au transport est un processus qui prend en moyenne huit semaines d'entraînement positif pour que l'animal l'identifie comme zone de sécurité biologique. Introduire un animal dans un transport neuf le jour du vol garantit une réponse de stress incontrôlable qui fera monter glycémie et lactate. Dans notre clinique au Pérou nous évaluons la fréquence cardiaque de base du patient dans sa caisse de voyage pour émettre un certificat de santé avec un critère d'aptitude réel et non purement administratif.</p>
<p>L'examen clinique pré-export doit inclure une révision dentaire et des coussinets, le stress chronique exacerbant tout foyer inflammatoire préexistant. Le SENASA exige que l'animal soit indemne d'ectoparasites et en bon état général, mais un professionnel doit aller au-delà et vérifier la stabilité cardiovasculaire à l'effort. Un chien avec souffles cardiaques subcliniques défaillera bien plus tôt face à l'hypoxie légère du vol si le stress d'embarquement a déjà épuisé sa réserve en oxygène myocardique.</p>
<p>La déparasitation interne doit utiliser des molécules sans effets secondaires émétiques, un épisode de vomissement dans le transport augmentant le risque de pneumonie d'aspiration. Le choix du principe actif doit s'aligner sur les fenêtres réglementaires du pays de destination (traitement contre Echinococcus multilocularis exigé par le Royaume-Uni ou la Norvège entre 24 et 120 h avant l'entrée). Une erreur dans cette fenêtre génère non seulement un problème documentaire mais oblige à répéter des actes vétérinaires qui stressent l'animal juste avant son vol le plus long.</p>
<p>Une erreur d'interprétation de l'état physiologique de votre animal peut conduire à une défaillance multi-organes ou à la mort subite pendant le transport international. Zoovet Travel audite la stabilité neuroendocrinienne des patients à Trujillo pour atténuer les signes de stress chez votre animal pendant le voyage et que faire pour les prévenir. Prenez rendez-vous pour une consultation technique au +51 979 620 402 ou +51 922 083 707 pour valider le protocole de voyage de votre compagnon. Assurez un atterrissage sain avec un appui clinique spécialisé.</p>""",
        },
    },
}

